a = str("Hello World")
b = int(10)
c = float(30)
d = list(("apple","orange","banana"))
e = tuple(("apple", "banana", "orange"))
f = dict(name = "John", age = 30)
g = set(("apple", "banana","orange", "cherry"))
h = bool(5)
i = range(5)

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(i)